import type { Report, Resource } from "./types";

export const CENTER = { lat: 20.2961, lng: 85.8245 }; // Bhubaneswar, Odisha

const now = Date.now();
const min = 60_000;

export const SEED_REPORTS: Report[] = [
  {
    id: "rep-1001",
    userId: "usr-citizen",
    source: "app",
    location: { lat: 20.3105, lng: 85.8412 },
    address: "Nayapalli, Bhubaneswar",
    type: "flood",
    description:
      "Water entered ground floor, 3 families trapped on the roof and water is still rising.",
    severity: "critical",
    severityScore: 9.2,
    hazardType: "flood",
    peopleAffected: "~14 people",
    status: "pending",
    createdAt: now - 8 * min,
    updatedAt: now - 8 * min,
  },
  {
    id: "rep-1002",
    userId: null,
    source: "sms",
    location: { lat: 20.2712, lng: 85.7935 },
    address: "Khandagiri, Bhubaneswar",
    type: "landslide",
    description: "Hill slope slipped onto the approach road, road blocked for 60 people.",
    severity: "high",
    severityScore: 7.4,
    hazardType: "landslide",
    peopleAffected: "~60 people",
    status: "pending",
    createdAt: now - 22 * min,
    updatedAt: now - 22 * min,
  },
  {
    id: "rep-1003",
    userId: "usr-citizen",
    source: "app",
    location: { lat: 20.2534, lng: 85.8607 },
    address: "Jatni Road, Bhubaneswar",
    type: "cyclone",
    description: "Roof sheets flying off, power lines down near the market.",
    severity: "medium",
    severityScore: 5.6,
    hazardType: "cyclone",
    peopleAffected: "unknown",
    status: "pending",
    createdAt: now - 41 * min,
    updatedAt: now - 41 * min,
  },
  {
    id: "rep-1004",
    userId: "usr-citizen",
    source: "ivr",
    location: { lat: 20.3298, lng: 85.8009 },
    address: "Patia, Bhubaneswar",
    type: "flood",
    description: "Ankle-deep water in the lane, drains overflowing.",
    severity: "low",
    severityScore: 3.1,
    hazardType: "flood",
    peopleAffected: "unknown",
    status: "resolved",
    createdAt: now - 180 * min,
    updatedAt: now - 90 * min,
  },
];

export const SEED_RESOURCES: Resource[] = [
  {
    id: "res-ndrf-1",
    type: "ndrf",
    name: "NDRF Team 04 — Boat Unit",
    location: { lat: 20.3021, lng: 85.8321 },
    address: "Unit-9, Bhubaneswar",
    capacity: 6,
    availableCount: 4,
    status: "available",
  },
  {
    id: "res-ndrf-2",
    type: "ndrf",
    name: "NDRF Team 11 — Search & Rescue",
    location: { lat: 20.2601, lng: 85.7822 },
    address: "Khandagiri Depot",
    capacity: 5,
    availableCount: 5,
    status: "available",
  },
  {
    id: "res-shelter-1",
    type: "shelter",
    name: "Cyclone Shelter — Nayapalli High School",
    location: { lat: 20.3088, lng: 85.8195 },
    address: "Nayapalli, Bhubaneswar",
    capacity: 400,
    availableCount: 260,
    status: "available",
  },
  {
    id: "res-shelter-2",
    type: "shelter",
    name: "Relief Camp — Jatni Community Hall",
    location: { lat: 20.2489, lng: 85.8712 },
    address: "Jatni Road, Bhubaneswar",
    capacity: 250,
    availableCount: 180,
    status: "available",
  },
  {
    id: "res-supply-1",
    type: "supply",
    name: "Supply Point — Dry Rations & Water",
    location: { lat: 20.2905, lng: 85.8501 },
    address: "Rasulgarh, Bhubaneswar",
    capacity: 1200,
    availableCount: 730,
    status: "available",
  },
  {
    id: "res-equip-1",
    type: "equipment",
    name: "Earth Mover & Debris Unit",
    location: { lat: 20.2755, lng: 85.7998 },
    address: "Khandagiri Yard",
    capacity: 3,
    availableCount: 2,
    status: "available",
  },
];
