import type { Report, Resource } from "./types";

export const CENTER = { lat: 22.1200, lng: 84.5400 }; // Rourkela, Odisha

const now = Date.now();
const min = 60_000;

export const SEED_REPORTS: Report[] = [
  {
    id: "rep-1001",
    userId: "usr-citizen-01",
    source: "app",
    location: { lat: 22.1312, lng: 84.5418 },
    address: "Sector 6, Rourkela",
    type: "flood",
    description:
      "Water entered ground floor, 3 families trapped on the roof and water is still rising.",
    severity: "critical",
    severityScore: 9.0,
    hazardType: "flood",
    peopleAffected: "~14 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 8 * min,
    updatedAt: now - 8 * min,
  },

  {
    id: "rep-1002",
    userId: null,
    source: "sms",
    location: { lat: 22.1452, lng: 84.5078 },
    address: "Panposh, Rourkela",
    type: "landslide",
    description:
      "Hill slope slipped onto the approach road, blocking access for approximately 60 people.",
    severity: "high",
    severityScore: 7.0,
    hazardType: "landslide",
    peopleAffected: "~60 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 22 * min,
    updatedAt: now - 22 * min,
  },

  {
    id: "rep-1003",
    userId: "usr-citizen-02",
    source: "app",
    location: { lat: 22.1048, lng: 84.5588 },
    address: "Uditnagar, Rourkela",
    type: "cyclone",
    description:
      "Roof sheets flying off and power lines are down near the market.",
    severity: "medium",
    severityScore: 5.0,
    hazardType: "cyclone",
    peopleAffected: "~25 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 41 * min,
    updatedAt: now - 41 * min,
  },

  {
    id: "rep-1004",
    userId: "usr-citizen-03",
    source: "ivr",
    location: { lat: 22.1565, lng: 84.5362 },
    address: "Bondamunda, Rourkela",
    type: "flood",
    description:
      "Ankle-deep water in the lane and drains are overflowing near residential houses.",
    severity: "low",
    severityScore: 3.0,
    hazardType: "flood",
    peopleAffected: "unknown",
    status: "resolved",
    citizenStatus: "safe",
    createdAt: now - 180 * min,
    updatedAt: now - 90 * min,
  },

  {
    id: "rep-1005",
    userId: null,
    source: "sms",
    location: { lat: 22.1165, lng: 84.5298 },
    address: "Sector 19, Rourkela",
    type: "flood",
    description:
      "Drain overflow has flooded the main road and several vehicles are stranded.",
    severity: "high",
    severityScore: 7.0,
    hazardType: "flood",
    peopleAffected: "~35 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 13 * min,
    updatedAt: now - 13 * min,
  },

  {
    id: "rep-1006",
    userId: "usr-citizen-04",
    source: "app",
    location: { lat: 22.0938, lng: 84.5488 },
    address: "Chhend Colony, Rourkela",
    type: "cyclone",
    description:
      "Strong winds damaged several rooftops and debris is blocking the service road.",
    severity: "high",
    severityScore: 7.0,
    hazardType: "cyclone",
    peopleAffected: "~45 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 29 * min,
    updatedAt: now - 29 * min,
  },

  {
    id: "rep-1007",
    userId: "usr-citizen-05",
    source: "app",
    location: { lat: 22.1268, lng: 84.5662 },
    address: "Civil Township, Rourkela",
    type: "flood",
    description:
      "Water level is rising around several houses near the low-lying road.",
    severity: "medium",
    severityScore: 5.0,
    hazardType: "flood",
    peopleAffected: "~20 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 35 * min,
    updatedAt: now - 35 * min,
  },

  {
    id: "rep-1008",
    userId: null,
    source: "ivr",
    location: { lat: 22.1515, lng: 84.5535 },
    address: "Basant Nagar, Rourkela",
    type: "landslide",
    description:
      "Mud and rocks have partially blocked the road after heavy rainfall.",
    severity: "medium",
    severityScore: 5.0,
    hazardType: "landslide",
    peopleAffected: "~30 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 52 * min,
    updatedAt: now - 52 * min,
  },

  {
    id: "rep-1009",
    userId: "usr-citizen-06",
    source: "app",
    location: { lat: 22.0875, lng: 84.5325 },
    address: "Jagda, Rourkela",
    type: "flood",
    description:
      "Water has entered multiple homes and residents are moving belongings to higher floors.",
    severity: "high",
    severityScore: 8.0,
    hazardType: "flood",
    peopleAffected: "~50 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 18 * min,
    updatedAt: now - 18 * min,
  },

  {
    id: "rep-1010",
    userId: null,
    source: "sms",
    location: { lat: 22.1385, lng: 84.5698 },
    address: "Koel Nagar, Rourkela",
    type: "cyclone",
    description:
      "Large tree fallen across the road and electrical lines are damaged.",
    severity: "medium",
    severityScore: 5.0,
    hazardType: "cyclone",
    peopleAffected: "~18 people",
    status: "pending",
    citizenStatus: "unknown",
    createdAt: now - 47 * min,
    updatedAt: now - 47 * min,
  },

  {
    id: "rep-1011",
    userId: "usr-citizen-07",
    source: "app",
    location: { lat: 22.1645, lng: 84.5205 },
    address: "Kuarmunda Road, Rourkela",
    type: "landslide",
    description:
      "Heavy rain caused soil movement beside the road and traffic has stopped.",
    severity: "high",
    severityScore: 7.0,
    hazardType: "landslide",
    peopleAffected: "~40 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 63 * min,
    updatedAt: now - 63 * min,
  },

  {
    id: "rep-1012",
    userId: null,
    source: "ivr",
    location: { lat: 22.1128, lng: 84.5735 },
    address: "Basanti Colony, Rourkela",
    type: "flood",
    description:
      "Water is accumulating rapidly near the colony entrance.",
    severity: "medium",
    severityScore: 5.0,
    hazardType: "flood",
    peopleAffected: "~28 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 71 * min,
    updatedAt: now - 71 * min,
  },

  {
    id: "rep-1013",
    userId: "usr-citizen-08",
    source: "app",
    location: { lat: 22.0985, lng: 84.5188 },
    address: "Hamirpur, Rourkela",
    type: "cyclone",
    description:
      "Multiple temporary structures damaged by strong winds.",
    severity: "high",
    severityScore: 7.0,
    hazardType: "cyclone",
    peopleAffected: "~55 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 84 * min,
    updatedAt: now - 84 * min,
  },

  {
    id: "rep-1014",
    userId: null,
    source: "sms",
    location: { lat: 22.1575, lng: 84.5488 },
    address: "Civil Township Extension, Rourkela",
    type: "flood",
    description:
      "Residents report rising water near the residential block.",
    severity: "low",
    severityScore: 3.0,
    hazardType: "flood",
    peopleAffected: "~12 people",
    status: "pending",
    citizenStatus: "unknown",
    createdAt: now - 96 * min,
    updatedAt: now - 96 * min,
  },

  {
    id: "rep-1015",
    userId: "usr-citizen-09",
    source: "app",
    phone: "+919178183129",
    location: { lat: 22.1275, lng: 84.5055 },
    address: "Vedvyas, Rourkela",
    type: "landslide",
    description:
      "Rock and mud debris have fallen onto the access road.",
    severity: "medium",
    severityScore: 5.0,
    hazardType: "landslide",
    peopleAffected: "~22 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 110 * min,
    updatedAt: now - 110 * min,
  },

  {
    id: "rep-1016",
    userId: "usr-citizen-10",
    source: "app",
    phone: "+919178183129",
    location: { lat: 22.0768, lng: 84.5585 },
    address: "Panposh Road South, Rourkela",
    type: "flood",
    description:
      "Low-lying houses are surrounded by water after continuous rainfall.",
    severity: "critical",
    severityScore: 9.0,
    hazardType: "flood",
    peopleAffected: "~75 people",
    status: "pending",
    citizenStatus: "needs_help",
    createdAt: now - 6 * min,
    updatedAt: now - 6 * min,
  },
];

export const SEED_RESOURCES: Resource[] = [
  {
    id: "res-ndrf-1",
    type: "ndrf",
    name: "NDRF Team 04 — Boat Unit",
    location: { lat: 22.1288, lng: 84.5655 },
    address: "Civil Township Response Base, Rourkela",
    capacity: 6,
    availableCount: 4,
    status: "available",
  },

  {
    id: "res-ndrf-2",
    type: "ndrf",
    name: "NDRF Team 11 — Search & Rescue",
    location: { lat: 22.1438, lng: 84.5162 },
    address: "Panposh Rescue Depot, Rourkela",
    capacity: 5,
    availableCount: 5,
    status: "available",
  },

  {
    id: "res-ndrf-3",
    type: "ndrf",
    name: "NDRF Team 07 — Rapid Response",
    location: { lat: 22.1085, lng: 84.5315 },
    address: "Uditnagar Sector 18 Response Base, Rourkela",
    capacity: 5,
    availableCount: 3,
    status: "available",
  },

  {
    id: "res-ndrf-4",
    type: "ndrf",
    name: "NDRF Team 15 — Flood Rescue",
    location: { lat: 22.0815, lng: 84.5505 },
    address: "Jagda Flood Response Base, Rourkela",
    capacity: 6,
    availableCount: 6,
    status: "available",
  },

  {
    id: "res-ndrf-5",
    type: "ndrf",
    name: "NDRF Team 19 — Rapid Deployment",
    location: { lat: 22.1565, lng: 84.5362 },
    address: "Bondamunda Response Base, Rourkela",
    capacity: 5,
    availableCount: 4,
    status: "available",
  },

  {
    id: "res-evacuation-1",
    type: "evacuation",
    name: "Evacuation Team 02 — Chhend",
    location: { lat: 22.0968, lng: 84.5515 },
    address: "Chhend Emergency Transport Unit, Rourkela",
    capacity: 3,
    availableCount: 3,
    status: "available",
  },

  {
    id: "res-evacuation-2",
    type: "evacuation",
    name: "Evacuation Team 05 — Panposh",
    location: { lat: 22.1398, lng: 84.5128 },
    address: "Panposh Emergency Transport Unit, Rourkela",
    capacity: 4,
    availableCount: 4,
    status: "available",
  },

  {
    id: "res-evacuation-3",
    type: "evacuation",
    name: "Evacuation Team 08 — Hamirpur",
    location: { lat: 22.0995, lng: 84.5215 },
    address: "Hamirpur Emergency Transport Unit, Rourkela",
    capacity: 4,
    availableCount: 3,
    status: "available",
  },

  {
    id: "res-evacuation-4",
    type: "evacuation",
    name: "Evacuation Team 10 — Vedvyas",
    location: { lat: 22.1265, lng: 84.5015 },
    address: "Vedvyas Emergency Transport Unit, Rourkela",
    capacity: 5,
    availableCount: 5,
    status: "available",
  },

  {
    id: "res-shelter-1",
    type: "shelter",
    name: "Cyclone Shelter — Sector 6 Community School",
    location: { lat: 22.1298, lng: 84.5365 },
    address: "Sector 6, Rourkela",
    capacity: 400,
    availableCount: 260,
    status: "available",
  },

  {
    id: "res-shelter-2",
    type: "shelter",
    name: "Relief Camp — Panposh Community Hall",
    location: { lat: 22.1462, lng: 84.5105 },
    address: "Panposh, Rourkela",
    capacity: 250,
    availableCount: 180,
    status: "available",
  },

  {
    id: "res-shelter-3",
    type: "shelter",
    name: "Emergency Shelter — Chhend Community Centre",
    location: { lat: 22.0968, lng: 84.5515 },
    address: "Chhend Colony, Rourkela",
    capacity: 300,
    availableCount: 210,
    status: "available",
  },

  {
    id: "res-shelter-4",
    type: "shelter",
    name: "Emergency Shelter — Hamirpur School",
    location: { lat: 22.0995, lng: 84.5215 },
    address: "Hamirpur, Rourkela",
    capacity: 350,
    availableCount: 190,
    status: "available",
  },

  {
    id: "res-shelter-5",
    type: "shelter",
    name: "Relief Shelter — Sector 19 Hall",
    location: { lat: 22.1165, lng: 84.5255 },
    address: "Sector 19, Rourkela",
    capacity: 280,
    availableCount: 160,
    status: "available",
  },

  {
    id: "res-supply-1",
    type: "supply",
    name: "Supply Point — Dry Rations & Water",
    location: { lat: 22.1115, lng: 84.5518 },
    address: "Uditnagar, Rourkela",
    capacity: 1200,
    availableCount: 730,
    status: "available",
  },

  {
    id: "res-supply-2",
    type: "supply",
    name: "Relief Supply Depot — Sector 19",
    location: { lat: 22.1188, lng: 84.5245 },
    address: "Sector 19, Rourkela",
    capacity: 900,
    availableCount: 510,
    status: "available",
  },

  {
    id: "res-supply-3",
    type: "supply",
    name: "Emergency Supply Point — Jagda",
    location: { lat: 22.0875, lng: 84.5348 },
    address: "Jagda, Rourkela",
    capacity: 1000,
    availableCount: 620,
    status: "available",
  },

  {
    id: "res-supply-4",
    type: "supply",
    name: "Relief Logistics Depot — Koel Nagar",
    location: { lat: 22.1385, lng: 84.5635 },
    address: "Koel Nagar, Rourkela",
    capacity: 850,
    availableCount: 430,
    status: "available",
  },

  {
    id: "res-equip-1",
    type: "equipment",
    name: "Earth Mover & Debris Unit",
    location: { lat: 22.1395, lng: 84.5075 },
    address: "Panposh Equipment Yard",
    capacity: 3,
    availableCount: 2,
    status: "available",
  },

  {
    id: "res-equip-2",
    type: "equipment",
    name: "Heavy Rescue Equipment Unit",
    location: { lat: 22.0995, lng: 84.5635 },
    address: "Chhend Equipment Yard, Rourkela",
    capacity: 4,
    availableCount: 3,
    status: "available",
  },

  {
    id: "res-equip-3",
    type: "equipment",
    name: "Road Clearance Unit",
    location: { lat: 22.1625, lng: 84.5215 },
    address: "Kuarmunda Road Equipment Yard",
    capacity: 4,
    availableCount: 2,
    status: "available",
  },

  {
    id: "res-equip-4",
    type: "equipment",
    name: "Heavy Machinery Unit",
    location: { lat: 22.1265, lng: 84.5015 },
    address: "Vedvyas Equipment Yard",
    capacity: 3,
    availableCount: 3,
    status: "available",
  },

  {
    id: "res-ndrf-deployed",
    type: "ndrf",
    name: "NDRF Team 03 — Currently Deployed",
    location: { lat: 22.1025, lng: 84.5455 },
    address: "Rourkela Response Zone",
    capacity: 5,
    availableCount: 0,
    status: "deployed",
  },

  {
    id: "res-equip-depleted",
    type: "equipment",
    name: "Debris Unit 02 — Depleted",
    location: { lat: 22.1335, lng: 84.5205 },
    address: "Rourkela Equipment Yard",
    capacity: 3,
    availableCount: 0,
    status: "depleted",
  },
];