/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ApiPublicReportsRouteImport } from './routes/api/public/reports'
import { Route as ApiPublicTwilioIncomingRouteImport } from './routes/api/public/twilio/incoming'
import { Route as ApiPublicTwilioSendRouteImport } from './routes/api/public/twilio/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReportsRoute = ApiPublicReportsRouteImport.update({
  id: '/api/public/reports',
  path: '/api/public/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioIncomingRoute = ApiPublicTwilioIncomingRouteImport.update({
  id: '/api/public/twilio/incoming',
  path: '/api/public/twilio/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSendRoute = ApiPublicTwilioSendRouteImport.update({
  id: '/api/public/twilio/send',
  path: '/api/public/twilio/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRoute
  '/citizen': typeof CitizenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-reports': typeof MyReportsRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/api/public/reports': typeof ApiPublicReportsRoute
  '/api/public/twilio/incoming': typeof ApiPublicTwilioIncomingRoute
  '/api/public/twilio/send': typeof ApiPublicTwilioSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRoute
  '/citizen': typeof CitizenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-reports': typeof MyReportsRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/api/public/reports': typeof ApiPublicReportsRoute
  '/api/public/twilio/incoming': typeof ApiPublicTwilioIncomingRoute
  '/api/public/twilio/send': typeof ApiPublicTwilioSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRoute
  '/citizen': typeof CitizenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-reports': typeof MyReportsRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/api/public/reports': typeof ApiPublicReportsRoute
  '/api/public/twilio/incoming': typeof ApiPublicTwilioIncomingRoute
  '/api/public/twilio/send': typeof ApiPublicTwilioSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority'
    | '/citizen'
    | '/forgot-password'
    | '/login'
    | '/my-reports'
    | '/register'
    | '/report'
    | '/api/public/reports'
    | '/api/public/twilio/incoming'
    | '/api/public/twilio/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authority'
    | '/citizen'
    | '/forgot-password'
    | '/login'
    | '/my-reports'
    | '/register'
    | '/report'
    | '/api/public/reports'
    | '/api/public/twilio/incoming'
    | '/api/public/twilio/send'
  id:
    | '__root__'
    | '/'
    | '/authority'
    | '/citizen'
    | '/forgot-password'
    | '/login'
    | '/my-reports'
    | '/register'
    | '/report'
    | '/api/public/reports'
    | '/api/public/twilio/incoming'
    | '/api/public/twilio/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorityRoute: typeof AuthorityRoute
  CitizenRoute: typeof CitizenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MyReportsRoute: typeof MyReportsRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  ApiPublicReportsRoute: typeof ApiPublicReportsRoute
  ApiPublicTwilioIncomingRoute: typeof ApiPublicTwilioIncomingRoute
  ApiPublicTwilioSendRoute: typeof ApiPublicTwilioSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reports': {
      id: '/api/public/reports'
      path: '/api/public/reports'
      fullPath: '/api/public/reports'
      preLoaderRoute: typeof ApiPublicReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/incoming': {
      id: '/api/public/twilio/incoming'
      path: '/api/public/twilio/incoming'
      fullPath: '/api/public/twilio/incoming'
      preLoaderRoute: typeof ApiPublicTwilioIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/send': {
      id: '/api/public/twilio/send'
      path: '/api/public/twilio/send'
      fullPath: '/api/public/twilio/send'
      preLoaderRoute: typeof ApiPublicTwilioSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorityRoute: AuthorityRoute,
  CitizenRoute: CitizenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MyReportsRoute: MyReportsRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  ApiPublicReportsRoute: ApiPublicReportsRoute,
  ApiPublicTwilioIncomingRoute: ApiPublicTwilioIncomingRoute,
  ApiPublicTwilioSendRoute: ApiPublicTwilioSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
